### ISSUE TITLE
Crash on application start

### ISSUE THREAD

**Issue by storedbox** [hankinsoft/SQLPro#244]
The application fails to open for me and the following exception shows up in Windows Event Viewer after each attempt.
```
Application: SQLitePro.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IsolatedStorage.IsolatedStorageException
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetRootDir(System.IO.IsolatedStorage.IsolatedStorageScope, System.Runtime.CompilerServices.StringHandleOnStack)
   at System.IO.IsolatedStorage.IsolatedStorageFile.InitGlobalsNonRoamingUser(System.IO.IsolatedStorage.IsolatedStorageScope)
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetRootDir(System.IO.IsolatedStorage.IsolatedStorageScope)
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetGlobalFileIOPerm(System.IO.IsolatedStorage.IsolatedStorageScope)
   at System.IO.IsolatedStorage.IsolatedStorageFile.Init(System.IO.IsolatedStorage.IsolatedStorageScope)
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(System.IO.IsolatedStorage.IsolatedStorageScope, System.Type, System.Type)
   at Microsoft.HockeyApp.HockeyClientWPFExtensions.Configure(Microsoft.HockeyApp.IHockeyClient, System.String)
   at SQLitePro.App+<OnStartup>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at SQLitePro.App.Main()
```
I have tried reinstalling via the store as well as both repairing and resetting via the "App settings" system dialog.

**Comment by hankinsoft** [comment]
You are seeing this crash as soon as you launch the app? Could you try rebooting? I've seen an issue with the WPF wrapped framework similar to this which was sorted by rebooting. In addition, could you send the full version of windows that you are using? Thanks!

**Comment by storedbox** [comment]
Yes, the crash occurs quickly enough after I open the application that a window never gets shown.

**Comment by storedbox** [comment]
Yes, the crash occurs quickly enough after I open the application that a window never gets shown. Rebooting has had no effect. I am running Windows 10 Pro Version 1809 (OS Build 17763.475).

**Comment by hankinsoft** [comment]
Hi, I've submitted a fix to the Microsoft App Store. It should hopefully be available within a day or so. I will post here again once I've confirmed its available.

**Comment by hankinsoft** [comment]
Latest version is available. If you get the chance, please give it a try and let me know if that sorts the startup crash.

**Comment by storedbox** [comment]
Yes, you've fixed my issue. Thank you!
